### ISSUE TITLE
14. In সাংগঠনিক কাঠামো page the list section should go down and the create section should go up. And in the create section parent box is missing

### ISSUE THREAD

**Issue by AnikaMollik** [collecteddoc/O-M#14]
![image](https://user-images.githubusercontent.com/52368063/62043336-e78db700-b221-11e9-8061-10ef7a7e23ab.png)

![14  Organization](https://user-images.githubusercontent.com/52368063/62042940-12c3d680-b221-11e9-9baf-3ce8cabdab50.PNG)

**Comment by teksoi** [comment]
fixed
