### ISSUE TITLE
7. in পদের মেয়াদ সংরক্ষণ page there are one problem 

### ISSUE THREAD

**Issue by AnikaMollik** [collecteddoc/O-M#24]
![image](https://user-images.githubusercontent.com/52368063/63246293-2bedff00-c284-11e9-94f5-a6a04861bc39.png)

**Comment by teksoi** [comment]
these were kept disabled intentionally as for this interface these properties are not subject to be changed. btw, inline edit is no more in use.

**Comment by ghost** [comment]
fixed
