### ISSUE TITLE
10. In শুন্যপদ page all edit and delete button are not warking

### ISSUE THREAD

**Issue by AnikaMollik** [collecteddoc/O-M#27]
![image](https://user-images.githubusercontent.com/52368063/63248199-9e60de00-c288-11e9-84c7-701d2f9c3c8b.png)

**Comment by teksoi** [comment]
edit is working

**Comment by teksoi** [comment]
delete action will be implemented later due to some business rules

**Comment by ghost** [comment]
Delete options are not available

**Comment by ghost** [comment]
Fixed. Edit Button is working.
