### ISSUE TITLE
11. ডকুমেন্ট >> ডকুমেন্ট পরের প্রকৃতি page there is a bug in the "edit" button

### ISSUE THREAD

**Issue by AnikaMollik** [collecteddoc/O-M#28]
![image](https://user-images.githubusercontent.com/52368063/63254236-31a01080-c295-11e9-9e54-77a3944e76cb.png)

**Comment by teksoi** [comment]
inline edit does not exists. form editing is used

**Comment by ghost** [comment]
fixed
