### ISSUE TITLE
14. In ডকুমেন্ট >> ডকুমেন্ট পরের প্রকৃতি page there is a one problem 

### ISSUE THREAD

**Issue by AnikaMollik** [collecteddoc/O-M#31]
![image](https://user-images.githubusercontent.com/52368063/63255429-9197b680-c297-11e9-8956-bb4fcc4cb946.png)

**Comment by teksoi** [comment]
inline editing no more exists. now it is done with form editing

**Comment by ghost** [comment]
fixed
