### ISSUE TITLE
Saves Record without Select Organization

### ISSUE THREAD

**Issue by ghost** [collecteddoc/O-M#38]
Path: **Organizational Structure**
**Issue:**  Drop down for **Select Organization**  is not showing, but records are being saved without selecting it. 
![no dropdown](https://user-images.githubusercontent.com/54391338/64147061-fa0e9800-ce40-11e9-88a7-6c8902e3d124.png)

**Comment by teksoi** [comment]
I mentioned it as known issue

**Comment by teksoi** [comment]
fixed

**Comment by ghost** [comment]
Fixed
