### ISSUE TITLE
Menubar highlight

### ISSUE THREAD

**Issue by ghost** [collecteddoc/O-M#40]
Path: Organizational Structure
Issue: Menu bar is not being highlighted on selection
![menubar not highlighting](https://user-images.githubusercontent.com/54391338/64148707-c6823c80-ce45-11e9-8d41-0dbc2a3b4394.png)

**Comment by teksoi** [comment]
its highlighted

**Comment by ghost** [comment]
This is just bold a little bit.. that is not user friendly. Please make it a different colour / of different shade

**Comment by ghost** [comment]
Fixed
