### ISSUE TITLE
Delete button does not work

### ISSUE THREAD

**Issue by ghost** [collecteddoc/O-M#43]
**Path:** Stabilization of Position
**Issue:** Delete button does not work.
![Delete Button does not work_stabilization of position](https://user-images.githubusercontent.com/54391338/64151354-00564180-ce4c-11e9-8b72-43394e57f5b3.png)

**Comment by teksoi** [comment]
delete action will be implemented later due to some business rules

**Comment by ghost** [comment]
Delete button is not available now..!

**Comment by ghost** [comment]
ALright
