### ISSUE TITLE
Delete Button is not Working

### ISSUE THREAD

**Issue by ghost** [collecteddoc/O-M#46]
**Path:**   **Stabilization of Position** , **Designation Changes** , **Vacancy,** **Add New All Documents, >Next Type of Documents ,** **Position Name**, **Organizational Structure**, **Office Equipment >All Equipments**
**Issue:**   Delete Button is not working.

**Comment by teksoi** [comment]
delete action will be implemented later due to some business rules

**Comment by ghost** [comment]
**Delete** button is not present

**Comment by ghost** [comment]
alright
