### ISSUE TITLE
Wrong Field Name

### ISSUE THREAD

**Issue by ghost** [collecteddoc/O-M#48]
**Path:**  Vacancy
**Issue:**  পদের প্রকৃতি should be renamed as পদের সংখ্যা
![poder sonkhya](https://user-images.githubusercontent.com/54391338/64161462-7f08aa00-ce5f-11e9-8beb-5a90150fad01.png)

**Comment by teksoi** [comment]
fixed

**Comment by ghost** [comment]
Fixed as , data type has been fixed.
