### ISSUE TITLE
Remove one module

### ISSUE THREAD

**Issue by ghost** [collecteddoc/O-M#52]
**Issue:**
1. This Add option is available in both the pages. 
2. Lets remove the Add New module.and Keep The **All Documents Module** for adding and seeing the Records.

![2019-09-03_15-55-25](https://user-images.githubusercontent.com/54391338/64165919-d27ef600-ce67-11e9-9da1-478b02f3d2db.png)

**Comment by teksoi** [comment]
add new document is removed

**Comment by ghost** [comment]
Solved. But new problems regarding this module is issued as a new bug.
