### ISSUE TITLE
7. In এনাম কমিটি কর্তৃক অনুমোদিত পদের বিবরণী Page, there are four problem

### ISSUE THREAD

**Issue by AnikaMollik** [collecteddoc/O-M#7]
1.data should be displayed as hierarchy tree view
2. Value is not loading
3. this should be year combo box (1971-current year)
4. Title is missing 

![image](https://user-images.githubusercontent.com/52368063/62029749-47c23000-b205-11e9-82d7-7c1a536e0ef1.png)

**Comment by teksoi** [comment]
all fixed

**Comment by ghost** [comment]
Not solved all.
Title is missing as well as the drop down is not showing the data properly.
![dropdown in the enam selection](https://user-images.githubusercontent.com/54391338/64934096-4fe43680-d86a-11e9-833e-dc5b35f28789.png)

**Comment by ghost** [comment]
Fixed
